"""Generate deterministic indexes for the Phoenix Knowledge Base."""

from __future__ import annotations

from pathlib import Path


SECTIONS = (
    ("Architecture", "architecture"),
    ("Specifications", "specifications"),
    ("Knowledge", "knowledge"),
    ("Decisions", "decisions"),
    ("Roadmap", "roadmap"),
    ("Bibliography", "bibliography"),
)


def markdown_files(root: Path) -> list[Path]:
    return sorted(
        path for path in root.rglob("*.md")
        if path.name.upper() != "INDEX.md"
    )


def generate_index(repository_root: Path | str) -> Path:
    repo = Path(repository_root)
    lines = [
        "# Phoenix Knowledge Base Index",
        "",
        "This index is generated by the Phoenix Build System.",
        "",
    ]

    for title, relative in SECTIONS:
        section_root = repo / relative
        lines.extend([f"## {title}", ""])
        if not section_root.exists():
            lines.append("_No documents available._")
            lines.append("")
            continue

        docs = markdown_files(section_root)
        if not docs:
            lines.append("_No documents available._")
            lines.append("")
            continue

        for path in docs:
            label = path.stem.replace("_", " ").replace("-", " ")
            target = path.relative_to(repo).as_posix()
            lines.append(f"- [{label}]({target})")
        lines.append("")

    output = repo / "knowledge" / "INDEX.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output
