param(
    [string]$RepoPath = "."
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "PROJECT PHOENIX - Phoenix Development Kit v1.0" -ForegroundColor Cyan
Write-Host ""

$repo = Resolve-Path $RepoPath
Set-Location $repo

if (-not (Test-Path ".git")) { throw "Geen git repository gevonden." }

Write-Host "Stap 1 - Status veilig vastleggen..." -ForegroundColor Yellow
git status --short | Set-Content -Encoding UTF8 "PHOENIX_PDK_v1_pre_install_status.txt"

$changes = git status --short
if ($changes) {
    git add -A
    git commit -m "chore: stabilize before phoenix development kit v1.0"
}

Write-Host "Stap 2 - PDK structuur aanmaken..." -ForegroundColor Yellow

$dirs = @(
    "project_phoenix/pdk",
    "project_phoenix/pdk/generators",
    "project_phoenix/pdk/validators",
    "project_phoenix/pdk/release",
    "project_phoenix/pdk/templates",
    "docs/project_phoenix/pdk",
    "outputs/pdk"
)

foreach ($d in $dirs) {
    New-Item -ItemType Directory -Force -Path $d | Out-Null
}

@'
"""
Phoenix Development Kit (PDK) v1.0
"""
__version__ = "1.0.0"
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/__init__.py"

@'
from pathlib import Path
from datetime import datetime
import json


class PhoenixSuiteGenerator:
    def __init__(self, root="suites"):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def generate_suite(self, suite_id: str, suite_title: str):
        suite_path = self.root / suite_id
        for name in ["core", "engines", "models", "schemas", "tests", "docs", "exports", "examples"]:
            (suite_path / name).mkdir(parents=True, exist_ok=True)

        (suite_path / "__init__.py").write_text(
            f"\"\"\"Project Phoenix Suite: {suite_title}\"\"\"\n__version__ = \"0.1.0\"\n",
            encoding="utf-8"
        )

        manifest = {
            "suite_id": suite_id,
            "suite_title": suite_title,
            "version": "0.1.0",
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "status": "generated_by_pdk"
        }

        (suite_path / "suite_manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )

        (suite_path / "docs" / f"{suite_id}_README.md").write_text(
            f"# {suite_title}\n\nGenerated by Phoenix Development Kit v1.0.\n",
            encoding="utf-8"
        )

        return manifest
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/generators/suite_generator.py"

@'
from pathlib import Path
import json


class PhoenixModuleGenerator:
    def generate_module(self, suite_id: str, module_id: str, module_title: str):
        suite_path = Path("suites") / suite_id
        module_path = suite_path / "engines" / f"{module_id}.py"
        module_path.parent.mkdir(parents=True, exist_ok=True)

        class_name = "".join(part.capitalize() for part in module_id.split("_")) + "Engine"

        code = (
            f"\"\"\"\n{module_title}\nGenerated by Phoenix Development Kit v1.0.\n\"\"\"\n\n"
            "from datetime import datetime\n\n\n"
            f"class {class_name}:\n"
            f"    MODULE_ID = \"{suite_id}.{module_id}\"\n"
            f"    MODULE_TITLE = \"{module_title}\"\n"
            "    VERSION = \"0.1.0\"\n\n"
            "    def run(self, payload=None):\n"
            "        return {\n"
            "            \"module_id\": self.MODULE_ID,\n"
            "            \"module_title\": self.MODULE_TITLE,\n"
            "            \"version\": self.VERSION,\n"
            "            \"ran_at\": datetime.now().isoformat(timespec=\"seconds\"),\n"
            "            \"payload\": payload or {},\n"
            "            \"status\": \"not_implemented_yet\"\n"
            "        }\n"
        )
        module_path.write_text(code, encoding="utf-8")

        schema_path = suite_path / "schemas" / f"{module_id}_schema.json"
        schema_path.parent.mkdir(parents=True, exist_ok=True)
        schema = {
            "module_id": f"{suite_id}.{module_id}",
            "module_title": module_title,
            "inputs": [],
            "outputs": [],
            "knowledge_sources": ["PKB", "BIB", "Knowledge Graph"],
            "tests": [],
            "exports": []
        }
        schema_path.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")

        return {"module_id": f"{suite_id}.{module_id}", "module_file": str(module_path)}
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/generators/module_generator.py"

@'
from pathlib import Path


class PhoenixTestGenerator:
    def generate_test(self, suite_id: str, module_id: str):
        test_path = Path("suites") / suite_id / "tests" / f"test_{module_id}.py"
        test_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.write_text(
            f"def test_{module_id}_placeholder():\n    assert True\n",
            encoding="utf-8"
        )
        return {"test_file": str(test_path)}
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/generators/test_generator.py"

@'
from pathlib import Path
from datetime import datetime
import json


class PhoenixSpecificationValidator:
    def validate_suite(self, suite_id: str):
        suite_path = Path("suites") / suite_id
        checks = {
            "suite_exists": suite_path.exists(),
            "manifest_exists": (suite_path / "suite_manifest.json").exists(),
            "core_exists": (suite_path / "core").exists(),
            "engines_exists": (suite_path / "engines").exists(),
            "schemas_exists": (suite_path / "schemas").exists(),
            "tests_exists": (suite_path / "tests").exists(),
            "docs_exists": (suite_path / "docs").exists()
        }
        result = {
            "suite_id": suite_id,
            "validated_at": datetime.now().isoformat(timespec="seconds"),
            "checks": checks,
            "overall_ok": all(checks.values())
        }
        out = Path("outputs/pdk")
        out.mkdir(parents=True, exist_ok=True)
        (out / f"{suite_id}_validation.json").write_text(
            json.dumps(result, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )
        return result
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/validators/specification_validator.py"

@'
from pathlib import Path
from datetime import datetime
import json


class PhoenixReleaseBuilder:
    def create_release_manifest(self, release_name: str, version: str):
        out = Path("outputs/pdk")
        out.mkdir(parents=True, exist_ok=True)
        manifest = {
            "release_name": release_name,
            "version": version,
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "status": "release_manifest_created",
            "generated_by": "Phoenix Development Kit v1.0"
        }
        (out / f"{release_name}_{version}_release_manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )
        return manifest
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/release/release_builder.py"

@'
from pathlib import Path
from datetime import datetime
import json

from project_phoenix.pdk.generators.suite_generator import PhoenixSuiteGenerator
from project_phoenix.pdk.generators.module_generator import PhoenixModuleGenerator
from project_phoenix.pdk.generators.test_generator import PhoenixTestGenerator
from project_phoenix.pdk.validators.specification_validator import PhoenixSpecificationValidator
from project_phoenix.pdk.release.release_builder import PhoenixReleaseBuilder


class PhoenixDevelopmentKit:
    def bootstrap_architectural_suite(self):
        suite = PhoenixSuiteGenerator().generate_suite("architectural", "Architectural Suite")

        modules = [
            ("project_intake", "Project Intake Engine"),
            ("program_of_requirements", "Programma van Eisen Engine"),
            ("space_schedule", "Ruimtestaat Engine"),
            ("floorplan_generator", "Plattegrondgenerator"),
        ]

        generated_modules = []
        for module_id, title in modules:
            generated_modules.append(PhoenixModuleGenerator().generate_module("architectural", module_id, title))
            PhoenixTestGenerator().generate_test("architectural", module_id)

        validation = PhoenixSpecificationValidator().validate_suite("architectural")
        release = PhoenixReleaseBuilder().create_release_manifest("architectural_suite_pdk_bootstrap", "0.1.0")

        result = {
            "pdk": "Phoenix Development Kit",
            "version": "1.0.0",
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "suite": suite,
            "modules": generated_modules,
            "validation": validation,
            "release": release
        }

        out = Path("outputs/pdk")
        out.mkdir(parents=True, exist_ok=True)
        (out / "pdk_v1_bootstrap_result.json").write_text(
            json.dumps(result, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )

        return result


if __name__ == "__main__":
    result = PhoenixDevelopmentKit().bootstrap_architectural_suite()
    print("Phoenix Development Kit v1.0 geïnstalleerd.")
    print("Architectural Suite bootstrap:", result["validation"]["overall_ok"])
'@ | Set-Content -Encoding UTF8 "project_phoenix/pdk/pdk.py"

@'
# Phoenix Development Kit (PDK) v1.0

## Doel

De PDK is de interne ontwikkeltooling van Project Phoenix.

## Onderdelen

- Suite Generator
- Module Generator
- Test Generator
- Specification Validator
- Release Builder

## Eerste bootstrap

PDK v1.0 maakt alvast de eerste Architectural Suite structuur aan met:

- Project Intake
- Programma van Eisen
- Ruimtestaat
- Plattegrondgenerator
'@ | Set-Content -Encoding UTF8 "docs/project_phoenix/pdk/PHOENIX_DEVELOPMENT_KIT_v1.md"

Write-Host "Stap 3 - PDK bootstrap uitvoeren..." -ForegroundColor Yellow
python -m project_phoenix.pdk.pdk

Write-Host "Stap 4 - Commit maken..." -ForegroundColor Yellow
git add project_phoenix/pdk suites/architectural docs/project_phoenix/pdk outputs/pdk PHOENIX_PDK_v1_pre_install_status.txt
git commit -m "feat: add phoenix development kit v1 and bootstrap architectural suite"

Write-Host "Stap 5 - Status tonen..." -ForegroundColor Yellow
git status

Write-Host ""
Write-Host "KLAAR: Phoenix Development Kit v1.0 is geïnstalleerd." -ForegroundColor Green
Write-Host "Voer daarna uit: git push" -ForegroundColor Green