from pathlib import Path
import json


class PhoenixModuleGenerator:
    def generate_module(self, suite_id: str, module_id: str, module_title: str):
        suite_path = Path("suites") / suite_id
        module_path = suite_path / "engines" / f"{module_id}.py"
        module_path.parent.mkdir(parents=True, exist_ok=True)

        class_name = "".join(part.capitalize() for part in module_id.split("_")) + "Engine"

        code = (
            f"\"\"\"\n{module_title}\nGenerated by Phoenix Development Kit v1.0.\n\"\"\"\n\n"
            "from datetime import datetime\n\n\n"
            f"class {class_name}:\n"
            f"    MODULE_ID = \"{suite_id}.{module_id}\"\n"
            f"    MODULE_TITLE = \"{module_title}\"\n"
            "    VERSION = \"0.1.0\"\n\n"
            "    def run(self, payload=None):\n"
            "        return {\n"
            "            \"module_id\": self.MODULE_ID,\n"
            "            \"module_title\": self.MODULE_TITLE,\n"
            "            \"version\": self.VERSION,\n"
            "            \"ran_at\": datetime.now().isoformat(timespec=\"seconds\"),\n"
            "            \"payload\": payload or {},\n"
            "            \"status\": \"not_implemented_yet\"\n"
            "        }\n"
        )
        module_path.write_text(code, encoding="utf-8")

        schema_path = suite_path / "schemas" / f"{module_id}_schema.json"
        schema_path.parent.mkdir(parents=True, exist_ok=True)
        schema = {
            "module_id": f"{suite_id}.{module_id}",
            "module_title": module_title,
            "inputs": [],
            "outputs": [],
            "knowledge_sources": ["PKB", "BIB", "Knowledge Graph"],
            "tests": [],
            "exports": []
        }
        schema_path.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")

        return {"module_id": f"{suite_id}.{module_id}", "module_file": str(module_path)}
