from pathlib import Path
from datetime import datetime
import json


class PhoenixSuiteGenerator:
    def __init__(self, root="suites"):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def generate_suite(self, suite_id: str, suite_title: str):
        suite_path = self.root / suite_id
        for name in ["core", "engines", "models", "schemas", "tests", "docs", "exports", "examples"]:
            (suite_path / name).mkdir(parents=True, exist_ok=True)

        (suite_path / "__init__.py").write_text(
            f"\"\"\"Project Phoenix Suite: {suite_title}\"\"\"\n__version__ = \"0.1.0\"\n",
            encoding="utf-8"
        )

        manifest = {
            "suite_id": suite_id,
            "suite_title": suite_title,
            "version": "0.1.0",
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "status": "generated_by_pdk"
        }

        (suite_path / "suite_manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False),
            encoding="utf-8"
        )

        (suite_path / "docs" / f"{suite_id}_README.md").write_text(
            f"# {suite_title}\n\nGenerated by Phoenix Development Kit v1.0.\n",
            encoding="utf-8"
        )

        return manifest
