from __future__ import annotations
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

@dataclass
class Acceptance:
    engine_id: str
    status: str
    registered_path: str | None
    sha256: str | None
    version_output: str
    notes: list[str]

def sha256_file(path: Path) -> str:
    h=hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda:f.read(1024*1024),b""):
            h.update(chunk)
    return h.hexdigest()

def load_registry(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def find_artifact(root: Path, names: list[str]) -> Path | None:
    lowered={n.lower() for n in names}
    for p in sorted(root.rglob("*")):
        if p.is_file() and p.name.lower() in lowered:
            return p
    return None

def register_portable(
    engine_id: str,
    source_root: Path,
    managed_root: Path,
    registry_path: Path,
    expected_sha256: str,
) -> Acceptance:
    registry=load_registry(registry_path)
    spec=registry["engines"][engine_id]
    artifact=find_artifact(source_root,spec.get("artifact_names",[]))
    if artifact is None:
        raise FileNotFoundError(f"No approved executable candidate found for {engine_id}")
    digest=sha256_file(artifact)
    if not expected_sha256 or digest.lower()!=expected_sha256.lower():
        raise ValueError(f"SHA-256 mismatch for {artifact.name}")
    target_dir=managed_root/engine_id/digest[:16]
    if target_dir.exists():
        shutil.rmtree(target_dir)
    shutil.copytree(source_root,target_dir)
    registered=find_artifact(target_dir,spec.get("artifact_names",[]))
    if registered is None:
        raise RuntimeError("Registered executable missing after copy")
    env_name=spec.get("environment_variable","")
    notes=[]
    if env_name:
        notes.append(f"Set persistent user environment variable {env_name} to {registered}")
    version=""
    args=[str(registered),*spec.get("acceptance_arguments",[])]
    try:
        cp=subprocess.run(args,text=True,capture_output=True,timeout=20,check=False)
        version=((cp.stdout or "")+"\n"+(cp.stderr or "")).strip()[:1000]
        status="REGISTERED" if cp.returncode in (0,1) else "REGISTERED_REVIEW_REQUIRED"
    except Exception as exc:
        status="REGISTERED_REVIEW_REQUIRED"
        notes.append(f"Acceptance command failed: {type(exc).__name__}")
    acceptance=Acceptance(engine_id,status,str(registered),digest,version,notes)
    (target_dir/"phoenix_engine_acceptance.json").write_text(
        json.dumps(asdict(acceptance),indent=2,sort_keys=True)+"\n",
        encoding="utf-8",newline="\n"
    )
    return acceptance

def install_ifcopenshell(registry_path: Path, python_executable: str | None=None) -> Acceptance:
    registry=load_registry(registry_path)
    spec=registry["engines"]["ifcopenshell"]
    py=python_executable or sys.executable
    package=spec["package"]
    cp=subprocess.run(
        [py,"-m","pip","install","--disable-pip-version-check",package],
        text=True,capture_output=True,check=False
    )
    if cp.returncode!=0:
        raise RuntimeError(cp.stdout+"\n"+cp.stderr)
    verify=subprocess.run(
        [py,"-c","import ifcopenshell; print(ifcopenshell.version)"],
        text=True,capture_output=True,check=False
    )
    if verify.returncode!=0:
        raise RuntimeError(verify.stdout+"\n"+verify.stderr)
    return Acceptance("ifcopenshell","INSTALLED",py,None,verify.stdout.strip(),[])

def write_environment_script(acceptances: list[dict[str,Any]], path: Path) -> None:
    lines=["# Generated by Project Phoenix v5.1.0","$ErrorActionPreference='Stop'"]
    for item in acceptances:
        env=item.get("environment_variable")
        value=item.get("registered_path")
        if env and value:
            escaped=str(value).replace("'","''")
            lines.append(f"[Environment]::SetEnvironmentVariable('{env}','{escaped}','User')")
            lines.append(f"$env:{env}='{escaped}'")
    lines.append("Write-Host 'PHOENIX ENGINE ENVIRONMENT VARIABLES CONFIGURED' -ForegroundColor Green")
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n")
